name: "Build Poker Firmware"
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v4
        with:
          submodules: true
        
      - uses: rrbutani/use-nix-shell-action@v1
        name: export flake
        with:
          devShell: .#build 
      # To make the environment in your flake's devShell available to future
      # steps:
      - uses: rrbutani/use-nix-shell-action@v1
        name: run make
        with:
          exportEnv: false
          interpreter: bash
          clearEnvForScript: true # `SOME_ENV_VAR` will not be visible; nor will
          script: |
            make
            make build/ikbc_poker2.bin
      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Poker2 firmware
          path: |
            ${{github.workspace}}/build/poker2.hex
            ${{github.workspace}}/build/poker2.bin
            ${{github.workspace}}/build/ikbc_poker2.bin
          if-no-files-found: error
